FROM golang:1.24-alpine AS build

WORKDIR /src
COPY gitee-userinfo.go ./
RUN CGO_ENABLED=0 GOOS=linux go build \
  -trimpath \
  -ldflags="-s -w" \
  -o /out/gitee-userinfo \
  ./gitee-userinfo.go

FROM scratch

COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=build /out/gitee-userinfo /gitee-userinfo

USER 65532:65532
ENTRYPOINT ["/gitee-userinfo"]
